### ISSUE TITLE
Support for reporting periods?

### ISSUE THREAD

**Issue by aminnausin** [robertogallea/pulse-api#2]
Hi, 

Is it possible to add the ?period= feature into the API URLs? I am not sure if it was supposed to work out of the box, but /api/pulse?period=7_days returns the same data as /api/pulse.

I've tried to implement a workaround by creating custom versions of the dashboard controller and root resources, but I haven't had much luck getting it to function correctly.

Any guidance or updates on this would be greatly appreciated!

Thanks

![image](https://github.com/user-attachments/assets/04132f16-ea86-489f-ab05-69d6309453b1)
![image](https://github.com/user-attachments/assets/35e80da1-2552-49b4-8369-3221671aa758)

**Comment by robertogallea** [comment]
~~Hi, this is certainly possible but wasn't the original purpose of the package. It was meant to show the instantaneous DB tables size. Indeed, it stores data in the `pulse_values` table instead of the `pulse_entries`.~~

~~What you are asking is a time series of the tables size along a period. This could be useful for sure. However, I think it would be somewhat cumbersome because it would require to show a line plot for each table (potentially dozens), and, if you are considering more than a bunch of tables, will soon become overwhelming to display.~~

~~I have no plans to implement it right now, but you are welcome to make a PR, or maybe, a whole new package.~~

**Comment by robertogallea** [comment]
Sorry, I totally misunderstood the "context". I thought you were referring to another package "pulse-db-size".

I was sure this package supported period but effectively I did not check... I will reopen the issue.

**Comment by robertogallea** [comment]
`Robertogallea\PulseApi\Http\Resources\PulseResource` uses the `Laravel\Pulse\Livewire\Concerns\HasPeriod` trait, which has the following property:

```php
    /**
     * The usage period.
     *
     * @var '1_hour'|'6_hours'|'24_hours'|'7_days'|null
     */
    #[Url]
    public ?string $period = '1_hour';
```

The `#[Url]` attribute is from Livewire and binds the property to the query string, which in turn is always used to retrieve pulse data, exactly as Pulse "web" does. It is weird it does not work... I will try to dig more into it.

Perhaps it works only for components. In this case, it could be sufficient to remove the attribute and use directly the `Request` object from the Service Container. Would you mind to give a try and make a PR? Thanks!

**Comment by aminnausin** [comment]
I don't know how LiveWire works so I might be wrong, but I think the #[Url] attribute doesn't work with API URLs because the LiveWire system is never loaded. Passing in the value from a query in the request makes it work. I made a pull request from my fork.

**Comment by robertogallea** [comment]
Please let me know if it works, so I can close the issue. Thanks

**Comment by aminnausin** [comment]
Sorry, I actually missed one line of code and put it in #4. My bad.

I don't know how to test a standalone laravel package like this because there are no pulse tables in the testing database and neither of the json structure tests can pass. Composer test failed on those two before I made any changes.

**Comment by robertogallea** [comment]
It was quite tricky for me too. I managed to do it using orchestra testbench package. You can give a look at this package github actions here https://github.com/robertogallea/pulse-api/blob/main/.github%2Fworkflows%2Ftests.yml#L28

Thanks!

**Comment by aminnausin** [comment]
Works now, thank you
